### ISSUE TITLE
MnM utils not recognized by Tabbychat

### ISSUE THREAD

**Issue by uszasty** [killjoy1221/TabbyChat-2#10]
I don't know if this is more suitable here or on MnMutils page, but this is happening when I try to install TabbyChat with liteloader: http://prntscr.com/6dymqf

**Comment by killjoy1221** [comment]
It is weird that this is happening. Can you post the liteloader log? Click where it says `liteloader` and click `LiteLoader Log`, then click `Upload Log`.

**Comment by uszasty** [comment]
Here is log: http://logs.liteloader.com/view/DY6jCKx?raw=2

**Comment by killjoy1221** [comment]
Can you test with the latest commit? I did some changes to the litemod.json in both projects.

**Comment by floogulinc** [comment]
Just FYI, removing the dependency line from litemod.json in the TabbyChat jar fixes this. It can operate without declaring the dependency, but would probably cause problems if you didn't have the dependency.

**Comment by uszasty** [comment]
Oh, yeah. I forgot about this actually, sorry. I found out that it was only occurring when using Windows XP, but since I got update to 7 I haven't run into this again. So yeah, anyway, it's working now for me.

**Comment by floogulinc** [comment]
Actually it does occur for me on OS X 10.9 so I had to remove the dependency from litemod.json.

**Comment by joen93** [comment]
It occurs on Unix and Linux systems too (tried on OS X and Ubuntu 15.04)

**Comment by killjoy1221** [comment]
I'm believing now that it is a bug in LiteLoader.

**Comment by killjoy1221** [comment]
I did some testing and it seems to be related to the order they are loaded. TabbyChat is loaded before MnmUtils, so the dependency check fails. Moving TabbyChat into the 1.8 folder seems to fix it.
