### ISSUE TITLE
Server side API

### ISSUE THREAD

**Issue by XakepSDK** [killjoy1221/TabbyChat-2#101]
Can you make server side api, so plugins like UltimateChat could manually manage tabs?

**Comment by killjoy1221** [comment]
How do you want this? Just allowing plugins to send messages directly to a tab?

**Comment by XakepSDK** [comment]
Yeah, also adding and removing tabs

**Comment by killjoy1221** [comment]
I don't think I want to give the server the ability to add or remove tabs willy-nilly, but adding a message to a channel will make it show if it's not set to be ignored.

**Comment by killjoy1221** [comment]
Finished.
