### ISSUE TITLE
Send messages to a specific tab

### ISSUE THREAD

**Issue by siva-u** [killjoy1221/TabbyChat-2#106]
Hey,

I was wondering if it was possible to send filtered messages to a specific tab, but hide it from the master tab?

It was possible on TabbyChat by unselecting "Send to all" and naming a specific tab.

![image](https://user-images.githubusercontent.com/15181320/60618183-6c291900-9dcd-11e9-9e1f-52079ee1e1d9.png)

Thanks!

**Comment by mattmess1221** [comment]
There is a setting to turn that in globally. If a message is filtered into
a channel, it will not be sent to the global channel.

**Comment by siva-u** [comment]
Where is that setting exactly? Can't seem to find it

**Comment by mattmess1221** [comment]
I believe it is in the advanced settings.

**Comment by siva-u** [comment]
Forgot to close this, thanks for the help!
