### ISSUE TITLE
Links cannot be clicked in 1.14

### ISSUE THREAD

**Issue by coztellation** [killjoy1221/TabbyChat-2#109]
A while ago I compiled the 1.14 version of this and had to stop using it due to the fact where it's not possible to click any links in chat
Kinda annoying for URLs but really annoying for /tpa and /pay that require links in chat

**Comment by mattmess1221** [comment]
Does it work in 1.15? There were lots of bugs before I updated.

**Comment by coztellation** [comment]
It seems I can't get it to load in 1.15, it might just be my setup but it just doesn't load.
Also, apologies for waiting 3 days to respond, I might have forgotten...
