### ISSUE TITLE
Broken Chat, Deleted Player Model

### ISSUE THREAD

**Issue by Heliosarc** [killjoy1221/TabbyChat-2#115]
No logs to give, more visual if anything.

How to recreate problem;

1) Downloaded latest Tabbychat 2 build : https://travis-ci.org/github/killjoy1221/TabbyChat-2/builds/662812842
2) Downloaded latest Kottle build: https://www.curseforge.com/minecraft/mc-mods/kottle/files/2895068
3) Both mods and only those two mods were inside .minecraft/mods
4) Made sure to have Forge 1.15.2-31.1.0
5) Launched the game normally, everything seems to work fine.
6) Create new world and enter said world.
7) Try to move around or type in chat.

You'll realize upon trying to move around or type in chat that there's a lot of problems. Firstly, typing in chat works, but when you hit enter, nothing comes out. 

When you swap your POV, you'll notice that your character is missing, meaning it's been deleted, disappeared somehow. It doesn't exist. However, you're still able to break blocks, unfortunately you're not able to do any commands so I wasn't able to see if it was the same way in creative mode. There are no block breaking animations, the blocks just instantly break as if you were a hacker with insta-break on, except the hack client is on steroids. (I'm not using a hack client)

Anyway to resolve this?

**Comment by Heliosarc** [comment]
I went ahead and tried more of TabbyChat2 to see if the mod itself functions. It does not.

1) Repeat all steps of the above text.
2) Right-click the main tab of the chat window once it's open, you'll notice that everything around you has stopped. I try opening one of the settings tabs, minecraft crashes

Here's a log file of this issue; https://pastebin.com/1hUK5mXp
Error Message given by Minecraft after the client crashes; "The game crashed whilst mouseclicked event handler
Error: kotlin.UninitializedPropertyAccessException: lateinit property serverSettings has not been initialized"

I had voiced this problem beforehand in a previous issue made earlier today that had been closed and had been said to be fixed.

>Whenever I try to move around, it won't let me, but doesn't crash. It's when I open chat that the crash happens. #114

**Comment by mattmess1221** [comment]
https://github.com/killjoy1221/TabbyChat-2/commit/e015062fc4742334ee9a945c12e48a78e5c2ea85

This should make sure the config directory exists before trying to write it. Your previous issue which was a `ClassDefNotFoundError` was caused by running it on the wrong version. Forge moved a class around.

**Comment by mattmess1221** [comment]
Be sure you're using the `-release` jar.  That one includes jazzy, which is used for spellcheck.

**Comment by Heliosarc** [comment]
Alright, everything seems to be working fine now. Thanks! Quick question though, when you move the chat window, is it supposed to be able to be moved off-screen instead of hitting the edge of the screen like it used to?

**Comment by mattmess1221** [comment]
The chat window will still bounce back in-bounds when you let go of the mouse.
