### ISSUE TITLE
Mouseover Tooltips, Default Text not working || Misaligned objects

### ISSUE THREAD

**Issue by Heliosarc** [killjoy1221/TabbyChat-2#116]
Whenever you mouse over specific areas where tooltips would be shown in previous versions, the tooltips don't show up.

Specifically, when creating a filter, you hover your mouse over .*, Aa, or &0 and nothing appears to help give the difference between the three options.

Default Text as in the text filled when viewing filters. When you create a filter and finish, hit done, move to create another filter or look at another filter, it'll look like it disappears. But it hasn't, it's like it's invisible, until you click on it to edit, then it appears again.

It's not just filters however, it's Ignored Channels, Channel Alias, Channel Prefix, Channel Cmd, Filter Name, Filter Destinations, Filter Sound Notification, Filter Expression. Any textbox that allows for input shares this problem.

Misaligned objects as in there'd be text boxes, text fields, and buttons misaligned such as the Anti Spam Prejudice or the......thing in the Advanced tab. It has a textbox that can be changed by arrow buttons, but has no text field......

No logs to give.

**Comment by Heliosarc** [comment]
Also, during filters or channels, when you're typing in one field and then swap to another field. For some reason, your text cursor stays at the previous field you were editing, and now there's two text cursors, one at the previous text field and now the new one at the current text field you're editing.

**Comment by mattmess1221** [comment]
I've temporally removed some features related to UI after some refactoring and rewriting. I'll add them back in the future.

**Comment by mattmess1221** [comment]
https://github.com/killjoy1221/TabbyChat-2/commit/5dd9b36604332bfb0ee6694c85ce4d75abe6b718
This should resolve the missing text. I've known about it for a while, but just haven't gotten around to fixing it.
