### ISSUE TITLE
Settings not being saved.

### ISSUE THREAD

**Issue by Heliosarc** [killjoy1221/TabbyChat-2#117]
Most settings are not being saved whenever I leave the server I customize them on. I had custom filters, channels, general settings, and server settings. When I log out after setting them up, they are reset to default. (As if I deleted the mod and started over.)

**Comment by Heliosarc** [comment]
The only thing I believe is being saved are the channels.

**Comment by Heliosarc** [comment]
When channels are created, you're not able to edit them since they don't show up in the channel list until after you leave the server and reset everything except the channels and then you can start editing. This goes for channels automatically created and manually created.

**Comment by mattmess1221** [comment]
Looks like only filters are having issues. They're being saved, but it seems they're not being loaded properly. I'll see if I can find the cause.

**Comment by b12arr0** [comment]
This is still happening in General and Server settings.
