### ISSUE TITLE
Tabbychat can't load big user dictionnary files

### ISSUE THREAD

**Issue by Pyeroh** [killjoy1221/TabbyChat-2#13]
All is in the title, but for more details, the game freezes when trying to load too big user dictionnary files (for example on of these http://sourceforge.net/projects/jazzydicts/files/jazzydicts/Dictionaries%201.0/)

**Comment by killjoy1221** [comment]
Firstly, wrong repo. You want http://github.com/killjoy1221/tabbychat

Secondly, The *user* dictionary isn't meant for things that size. It's meant for custom words that you use a lot, not entire languages. I can't help you if you want to use another language.
