### ISSUE TITLE
Maybe - Create compatibility transformer

### ISSUE THREAD

**Issue by killjoy1221** [killjoy1221/TabbyChat-2#15]
Lots of mods extend GuiChat in order to add things to chat without actually replacing it. It is possible to do this using a render event for some of these.  For others, it is necessary, but because TabbyChat also extends GuiChat, only one can be used, and TabbyChat usually wins.

To add compatibility with these mods, I want to create a transformer to make those classes extend GuiChatTC instead of GuiChat. Hopefully, this would resolve issues with these mods.

Mods that I know of that use this method are:
- Macros
- ~~EiraIRC~~
- Aether
- Prattle (partial maybe)

**Comment by blay09** [comment]
No longer needed for EiraIRC - it lets TabbyChat take over the chat by default and sets up tabs to be used with the /irc msg command. :)

**Comment by killjoy1221** [comment]
I've decided that this would likely break more things than it fixes.
