### ISSUE TITLE
Future - External chat window

### ISSUE THREAD

**Issue by killjoy1221** [killjoy1221/TabbyChat-2#16]
I want to create a window outside of the minecraft game to optionally send all the chat to. It will have tabs and whatnot. I'm not going to start on this for a while, perhaps 2.1, so feel free to discuss what you would like this window to feature.

**Comment by onbjerg** [comment]
The Minecraft font. Really.

**Comment by killjoy1221** [comment]
How about customizable fonts?

**Comment by Cecer** [comment]
This will be **hugely** useful for my day to day activities. As a moderator on a very large Minecraft server I have to deal with a huge amount of chat from many different sources.  I full support this feature!

As you haven't really had any feedback on potential features here I'll list a few as food for thought.

* An always on top option so the chat window remains above other windows at all times.
* This could be a reasonable compromise to #26. Multiple chat boxes would really help keep track of multiple concurrent conversations even if they are external windows. They might even be better in some ways as they could go on to another monitor and free up some game real estate.
*Allowing a key to be configured to put focus on a certain window's text input. This way you could have the same kind of functionality we have with the vanilla chat but it would bring an external window on top and focus the input into the input field. Pressing escape in the text input would return the game to focus just like the standard chat would. Example: I could configure G to type into guild chat and P to type into party chat.

**Comment by mattmess1221** [comment]
This has become difficult to do since Minecraft switched to LWJGL3 and GLFW. Maybe someone else can make a mod that passes chat to a local socket that a separate program can read.
