### ISSUE TITLE
Client crashes when pressing 'T'

### ISSUE THREAD

**Issue by JamesJ99** [killjoy1221/TabbyChat-2#18]
Hi,
When I press 'T' I get this error:

http://paste.md-5.net/jawonekade.avrasm

I have the following mods installed; https://i.jamesj.me/YLRsRwt7.png (and MnM utils and TabbyChat [removed as I am now using Minecraft without those mods]). 
Any ideas?

**Comment by killjoy1221** [comment]
Tabbychat isn't really in the stacktrace, so I would have to blame macros. I've use macros without crashing, so I don't think it's the issue.

**Comment by killjoy1221** [comment]
Where did you get the macros mod? The filename doesn't look official. It's supposed to be mod_macros_0.11.1_for_1.8.litemod

Did you get it from some website like 9minecraft?

**Comment by killjoy1221** [comment]
I've had a conversation with Mumfrey and he said that crash would only happen if Macros has been tampered with. Mainly, the permissions system. Download the official version [here](http://eq2.co.uk/minecraft/mods/prerelease/).

**Comment by JamesJ99** [comment]
That crash only happened when I had TabbyChat and MnM-Utils installed (both from your blogspot), I've re-downloaded Macros. Testing it now.
