### ISSUE TITLE
Chat messages not being submitted

### ISSUE THREAD

**Issue by Cynthetik** [killjoy1221/TabbyChat-2#22]
I am having issues with the new tabby chat. It seems that when I log into a server, I am able to send about 2-4 messages before I am unable to submit more and I don't think anyone can receive the messages I send them. I was unable to send messages until I restarted the client, and even then the issue will repeat after a few messages sent.

This video should demonstrate the bug.
http://tinypic.com/r/ajl192/8

**Comment by killjoy1221** [comment]
Can you post the log up until it stops working? There may be an error or stacktrace.

**Comment by Cynthetik** [comment]
How do I post the logs?

**Comment by killjoy1221** [comment]
Preferably via pastebin.

**Comment by Cynthetik** [comment]
I mean, where can I get the logs to post it in?

**Comment by killjoy1221** [comment]
In the launcher, edit your profile to keep it open after the game launches

**Comment by Cynthetik** [comment]
http://pastebin.com/qRXT5wuG

**Comment by killjoy1221** [comment]
Can you post a log using the default resource pack? Optifine is spamming the log because of errors. Remember, it needs to start up using the default.

**Comment by Cynthetik** [comment]
http://pastebin.com/srZyTZYP

I think I see what happened. The chat stopped working when I began to move. I was able to send messages when I stood still.

**Comment by killjoy1221** [comment]
I'm tired of failing to discuss this over GitHub. Can you get on IRC? 

http://webchat.esper.net/?channels=TabbyChat

**Comment by Cynthetik** [comment]
http://pastebin.com/ycbEGYdK

Here's the chat test with TabbyChat with no other mods installed. I don't see any errors in the logs.

**Comment by killjoy1221** [comment]
I've determined that the log isn't helping me any, so there's no need to post any more. Your best bet is to get someone who know what they're doing *and* is able to reproduce this and get them to post here.

**Comment by Cynthetik** [comment]
I will get a few players to post here. They have also reproduced the issue.

https://www.lordofthecraft.net/topic/127701-for-those-of-you-with-issues-with-tabby-chat/#entry1226275

**Comment by killjoy1221** [comment]
I looked at that video that was posted, and it seems to me that nobody understands how TabbyChat works. The tabs control what comes in, not what goes out. If you are in some channel, it is not going to show you in some other tab even if you're in it.

For now, if you want to speak in a channel, you have to do `/ch qm <channel> <msg>` or actually join the channel. (In herochat at least).

**Comment by Cynthetik** [comment]
At 2:06 he reproduced the problem. His default channel was the OOC channel. At 1:56, he clicked on the * tab which would view the messages of all of the channels he joined. He already reproduced this problem then. That wasn't the best video, but here's more videos.

This is my video. From launch to log in. I didn't switch channels, and only sent a tell. After a while I was unable to send anymore messages on the server. https://vid.me/7Yfx

This other player reproduced this issue as well. https://www.youtube.com/watch?v=DE9t1hwq3Tw&feature=youtu.be

I have reproduced the issue in singleplayer. So I will be uploading that soon.

**Comment by Cynthetik** [comment]
I locked it? Sorry about that.

**Comment by Cynthetik** [comment]
So wait, you found the problem?

**Comment by killjoy1221** [comment]
You didn't lock it, I fixed it. Now the chat shouldn't stay locked up if you hit enter without typing anything in chat.

**Comment by Cynthetik** [comment]
Do I redownload the file or wait until te next update?

**Comment by killjoy1221** [comment]
I'm going to make another release soon. Stay tuned.
