### ISSUE TITLE
Beta 2a Issues

### ISSUE THREAD

**Issue by i-TP** [killjoy1221/TabbyChat-2#23]
Following are the issues I have found with the new Beta:
- Unable to Delete tabs (when choosing "Forget" it removes them from setting but not the chat itself.
- It seems as though the flags are not working correctly, not receiving notifications for flags that have audio notification set
- Not a bug: Towny Chat is not included, making Tabbychat think that towns/nations deserve their own chat.
- WIll post more as they are found

**Comment by killjoy1221** [comment]
Forgetting tabs not removing them from chat is an oversight on my part. I'll fix that up soon.

Sound notifications aren't implemented yet. Before I do that, I want to figure out a way to select sounds. I'll probably just do it the same way tabbychat 1 did.

Can you elaborate on Towny? It can probably be fixed when I implement ignoring channels.

In the future, can you create 1 report per issue? It makes it easier on me to keep track of things. Alternatively, use checkboxes.
```
- [ ] uncheck
- [x] check
```
- [ ] uncheck
- [x] check

**Comment by killjoy1221** [comment]
89e64b26133e863ee18d8da6015c1e370fdb0c9d

**Comment by killjoy1221** [comment]
Is everything you listed resolved? I'd like to close this.

**Comment by killjoy1221** [comment]
Reply or create a new issue if you still have issues.
