### ISSUE TITLE
Channels for Private messages

### ISSUE THREAD

**Issue by adzjwarner** [killjoy1221/TabbyChat-2#24]
In the previous version, sending or receiving a PM to or from a player would create a new tab for that player, and automatically prefix messages with /msg <username>.

Is this broken, or is it not implemented yet?

Thanks for the great work so far!

**Comment by killjoy1221** [comment]
This is implemented and works fine. What's the format of the message you're receiving?

**Comment by adzjwarner** [comment]
Hmm, interesting. 

 They do not arrive in brackets or anything just "From <user>: " and "To <user>: "
