### ISSUE TITLE
Variables for use in regex patterns

### ISSUE THREAD

**Issue by zedwick** [killjoy1221/TabbyChat-2#25]
I'd like to be able to use variables in my regex patterns:

%player% - My current player name

**Comment by killjoy1221** [comment]
Are there any other variables you want to use? I'd like to add them all at once rather than later.

**Comment by zedwick** [comment]
I honestly couldn't think of any others I'd find useful, other variables you could add would be:

%server% - serverip/port
%onlineplayer% - something to check for string matching any online player name

I could see %onlineplayer% being useful for creating custom PM rules, but I don't think it would work on a BungeeCord network-wide messaging system which is where I would be using it.

**Comment by killjoy1221** [comment]
Usage:  ${player}
