### ISSUE TITLE
TC Beta 2: Does not continue chat in appropriate section when exceeding normal chat length

### ISSUE THREAD

**Issue by veteranmina** [killjoy1221/TabbyChat-2#27]
When I am chatting with a pre-command of /r (for reply), it will reply to the user correctly until I hit the normal max chat limit. Once it hits that limit it does not repeat the pre-command of /r but rather posts the rest normally. 
Pre TC 2 had this built in. :-)

**Comment by killjoy1221** [comment]
Because I have no way of knowing what every parameter does, I'm limiting non-prefixed messages to 1 send.  If your message *is* prefixed, it will work as expected.
