### ISSUE TITLE
Channels loaded from settings don't have name or alias.

### ISSUE THREAD

**Issue by killjoy1221** [killjoy1221/TabbyChat-2#28]
They get saved correctly, but they don't get applied when loaded.

**Comment by PromoFaux** [comment]
Huh. I *think* I was just about to submit this as an issue :)

On the latest builds, Channels appear to be working correctly on first run, but subsequent runs cause the client to crash when you:

 - Right click channel to open channel settings
 - Click on the empty box that represents the channel in the settings screen.

The saved channels appear to have a null name.

**Comment by PromoFaux** [comment]
Another bug, possibly relating to this, in the latest build.
If I click onto a channel the game crashes. Crash log: http://pastebin.com/6RUmU9ZQ

Also tried with all other mods unloaded : Crash-log http://pastebin.com/7JTdKmAs

And the same again with resource pack unloaded.

**Comment by killjoy1221** [comment]
Yes, that was caused by this. It too is fixed.

**Comment by PromoFaux** [comment]
This was in snapshot 30.
Channels loaded OK between sessions, but actually clicking on them causes the client to crash.

**Comment by killjoy1221** [comment]
Delete your configs.  If you know how, delete the channels object in the server settings.

**Comment by PromoFaux** [comment]
That cleared it up until I restarted the client

**Comment by killjoy1221** [comment]
Try snapshot 31 once it finishes building.
363b4d47143899d10def9c330a3f644439e2947b

**Comment by PromoFaux** [comment]
Will try tomorrow, time for bed!

**Comment by killjoy1221** [comment]
If it doesn't work, create a new issue. This one was for the channel names being null.

**Comment by PromoFaux** [comment]
Just to let you know, it worked.
