### ISSUE TITLE
odd crash at client login

### ISSUE THREAD

**Issue by kreezxil** [killjoy1221/TabbyChat-2#31]
With the mods by mattDahEpic, namely Auto Ore Dictionary Converter and mattDahEpic core, your mod caused the following religiously at client login.

client crash report: https://gist.github.com/kreezxil/187626cda2e6beec3dc9#file-crash-report

client fml log: https://gist.github.com/kreezxil/187626cda2e6beec3dc9#file-fml-client-latest

I took out matt's mods and the problem went away, so I figured it was just matt's mods. But then occasionally at client login I'll get an issue that I can't connect and what's in the crash report is spammed in the fml log and console of the client but the client doesn't crash, relogging into the dedicated server resolves the issue.

Specifically the error that appears in the console is now: https://gist.github.com/kreezxil/e21ba409eb42ffaa0785#file-console-spamming-error-that-prevents-login-on-client-first-run

**Comment by killjoy1221** [comment]
I think I have a solution for the first error you're getting, but the second one might be caused by an error in your environment. I think it's your server data that's doing it. Does it happen when you join another server you've joined before or just that one?

**Comment by kreezxil** [comment]
Just this one. It's my own mega pack. More info at www.Kreezcraft.com

-----Original Message-----

**Comment by killjoy1221** [comment]
Then deleting the server's configs should fix it. If you don't want to delete everything, just data.gz will do.

Your configs should be located in `.minecraft/config/TabbyChat2/multiplayer/<serverip>/`

**Comment by kreezxil** [comment]
Thanks. I'll try that tomorrow.

-----Original Message-----

**Comment by robertquitt** [comment]
This fix worked for me! I had TabbyChat installed before, looks like the persistent config files were messing with the new install.

**Comment by kreezxil** [comment]
Ok, I tried that and it didn't help.

**Comment by robertquitt** [comment]
Ok I found a fix for me. You need to make sure you have the very latest version of MnM-utils. The one posted on mc forums is outdated for tabbychat. You need to find the latest version from a different website.

**Comment by killjoy1221** [comment]
It's built with tabbychat whenever I commit, so it can be found alongside
the drone builds.

**Comment by killjoy1221** [comment]
That last crash was actually caused by what I believe is a vanilla bug. Whenever the client tries to serialize a `show_entity` hover event, it messes up and just becomes `{}`, which it is unable to reserialize. I've added a safeguard against this by removing them.

7dffaa4859f5433cecb197f35087ee3c10c6f28b

**Comment by killjoy1221** [comment]
Is this still an issue?

**Comment by kreezxil** [comment]
No

-----Original Message-----
