### ISSUE TITLE
Expose ChatBox.getBoundsX(), .getBoundsY(), .getChatScale() to API

### ISSUE THREAD

**Issue by blay09** [killjoy1221/TabbyChat-2#32]
Need this to make EiraMoticons compatible without touching your internal classes.

**Comment by killjoy1221** [comment]
Should this be enough for you? c273da2ee924ca699ef151297a8349c19333aee3

**Comment by blay09** [comment]
Almost, however I specifically need the x and y position of the chat window as well as the chat scale to make sure things are positioned correctly.

See https://github.com/blay09/EiraMoticons/blob/master/src/main/java/net/blay09/mods/eiramoticons/addon/TabbyChatContainer.java for the implementation for TabbyChat 1 (using internal classes there though).

**Comment by killjoy1221** [comment]
Use something like this.
```java
import mnm.mods.util.gui.GuiPanel;
import mnm.mods.tabbychat.api.TabbyAPI;

GuiPanel chatbox = TabbyAPI.getAPI().getGui().asGui();
int x = chatbox.getBounds().x;
int y = chatbox.getBounds().y;
```

**Comment by blay09** [comment]
But if your API depends on another mod that's not dealt with using the same care as an API regarding changes then you've completely destroyed the point of having a public API.

I am trying to avoid using internal classes.

**Comment by killjoy1221** [comment]
Well I made the utils a separate library because it was more general was not likely to be updated as often.

In any case, how's this? f8ee75218e4994898de204300b11e5025b75e7df

**Comment by blay09** [comment]
That's perfect, thanks!

**Comment by killjoy1221** [comment]
Do you still need this open or is it resolved now?
