### ISSUE TITLE
Cursor is not in correct location

### ISSUE THREAD

**Issue by veteranmina** [killjoy1221/TabbyChat-2#35]
After typing anything in chat, the cursor becomes inaccurate if trying to relocate

**Comment by veteranmina** [comment]
I am using tabbychat 2.0.0-beta-snapshot.92.litemod, mnm-util-0.3-snapshot.92.litemod and macros-compat-1.0.1.litemod

**Comment by killjoy1221** [comment]
dfa595eb478f8d7fec6805798552ad96ec64b139

I think that's the issue you're talking about, but I'm not sure. Is it with the actual chat or the chat input?

**Comment by veteranmina** [comment]
Sorry for not answering back earlier. Quite busy with work and family. It is the input chat, anytime you type it slowly starts to go offtrack of the next character.

**Comment by killjoy1221** [comment]
I've already fixed it. Can you test?

**Comment by killjoy1221** [comment]
Somewhat related.
a38e15908320d40b013df85d930a4ce1c708585f
