### ISSUE TITLE
Different chat visibility options.

### ISSUE THREAD

**Issue by Fortifier42** [killjoy1221/TabbyChat-2#40]
I feel that the current way the chat is visibility settings are a bit limited, and thus propose 3 new options:

- [ ] Always Show
> This will add the ability to ALWAYS show the chat box, including tabs and possible the input box. 
> This will allow you to always see what is happening in the chat.

- [ ] When Active
> This will display the chat box when a new message is received or sent.
> The chat box will fade away after a set amount of time (this is the current response the chat box has).
> The fade-delay should have a control in the menu, rather than needing to manually edit the config.

- [ ] Never Show
> This will always hide the chat box, regardless of whether a message has been received.
> The chat box will still show when you type a message though, and hide instantly after it has been sent.

It would be good to have a button or drop-down list to select this option, along with the ability to bind a key to it - for easy changes while playing.

**Comment by killjoy1221** [comment]
826b9f7

**Comment by Fortifier42** [comment]
This isn't infact fixed. Now the chat box stays open, with the cursor inside it.. rather than simply showing like the default Minecraft chat does. I would like for the ability to simply **show** the chat box without needing to be typing into it.

**Comment by killjoy1221** [comment]
I think what you want is a configurable fade time. This is there, you you have to  edit the config manually.

`advanced.fadeTime`: It's in ticks.

**Comment by Fortifier42** [comment]
I don't want it to fade at all. I want it permanently displayed unless the HUD is hidden. :) I just felt that fade is a feature other people would want.

**Comment by killjoy1221** [comment]
If you set the fade high enough, it won't fade at all.
