### ISSUE TITLE
Chat box should be positioned from bottom left of screen

### ISSUE THREAD

**Issue by Fortifier42** [killjoy1221/TabbyChat-2#41]
The chat window should be anchored the bottom-left corner of the screen, similar to the default Minecraft chat window.
The current TabbyChat-2 setup means the window will resize or move itself to fit, then reposition badly afterwards.

The issue is demonstrated here: https://dl.dropboxusercontent.com/u/4208005/capture.mp4

**Comment by killjoy1221** [comment]
Let me know if there are any issues with this.

**Comment by killjoy1221** [comment]
Looks like there's still issues, but only when the scaling changes.

**Comment by killjoy1221** [comment]
caed459
