### ISSUE TITLE
Filtering not hiding chat? 

### ISSUE THREAD

**Issue by Teku16** [killjoy1221/TabbyChat-2#42]
![mc_issue](https://cloud.githubusercontent.com/assets/6700497/12123009/6be30cc6-b3ac-11e5-8259-374a87ba4f96.png)
This should be stripped from my special chat window, this is the regex I'm using:

^The shop is loading$|^Opening shop of player$

yet it still shows up. Am I doing it wrong or is this a bug?

**Comment by killjoy1221** [comment]
The issue is with your regex. You're not remembering for the channel.

![](http://i.imgur.com/cFch3PE.png)

**Comment by killjoy1221** [comment]
Use `^\[MinePact Inc\.\] (The shop is loading|Opening shop of player) .*$`

**Comment by Teku16** [comment]
Okay sorry for the issue request then! I guess my regex needs work ._. Thanks for answering AND providing me with a fix <3
