### ISSUE TITLE
compatibility issues 

### ISSUE THREAD

**Issue by Bluesw** [killjoy1221/TabbyChat-2#43]
could please re add support for the mod "Color Code Gui" by NukeDuck in early beta versions it worked flawlessly with the mod and allowed me to have really smart Unicode symbols and allowed easy access to color codes in chat box i really miss being able to inject the nuke/plane unicode in chat when im chatting to my friends thanks for reading this i look forward to your reply :)

**Comment by killjoy1221** [comment]
I'm going to have to say no for now. With the way that mod works right now, it would be difficult to add compatibility. It would actually be easier to create a new mod that works because it's so simple..
