### ISSUE TITLE
Messages with hooverable text.

### ISSUE THREAD

**Issue by Done84** [killjoy1221/TabbyChat-2#45]
When messages have hooverable stuff (not sure if its json) tabbychat cant catch the message.

Example: My message plugin has hoverable and clickable things in /msg and although its formatted that same way as essentials tabbychat won't catch the /message.

http://prntscr.com/a8t56r
http://i.imgur.com/nyKFcg9.png

**Comment by killjoy1221** [comment]
This isn't related to hovering. The message that you want to be detected doesn't have a space in it. You'll need to use a custom filter to catch it.

pattern: `^\[(?:(.+)->me|me->(.+))\]`  
destinations: `$1, $2`

Something like that will do.

**Comment by Done84** [comment]
Wow... I don't know where you saw a space there(http://prnt.sc/a8tpc9), but it totally worked. 
Thank you so much sir.

**Comment by Done84** [comment]
Ups... I still need some help. I didn't notice it creates 2 tabs.

When I message player its opens a tab named ** [ $2]**
http://prntscr.com/a8tvul

If player messages me it opens a tab with his name and another named [ $2]
http://prntscr.com/a8tvlg

**Comment by killjoy1221** [comment]
try removing the space after the comma.

**Comment by Done84** [comment]
I LOVE YOU! It worked, i noticed that everytime i click "done" when editing the filter it auto adds a space after the comma, i worked around it thought.
