### ISSUE TITLE
MapWriter Large Map Displaying

### ISSUE THREAD

**Issue by Its-its** [killjoy1221/TabbyChat-2#47]
translate doesn't let mapwriter's large gui (keybind M) display; removing it fixes the problem though.

https://github.com/killjoy1221/TabbyChat-2/blob/master/src/main/java/mnm/mods/tabbychat/core/GuiNewChatTC.java#L53

**Comment by killjoy1221** [comment]
918f0454c8f37e1e896c818aa56c68eb7fe7dee1

Try it now. https://drone.io/github.com/killjoy1221/TabbyChat-2/files

**Comment by Its-its** [comment]
perfecto
