### ISSUE TITLE
Chat Time options

### ISSUE THREAD

**Issue by veteranmina** [killjoy1221/TabbyChat-2#5]
(Just helping here for pointers)
Chat time option does not work, settings have been changed in multiple ways to ensure issue is replicated.

**Comment by killjoy1221** [comment]
The question is how I'm going to handle this. Should I make it multi row or have it scrolling?

**Comment by veteranmina** [comment]
Hmmm, could it be possible to make it an option between the two? I personally would like it to scroll as it would keep chat in full view. Since I'm a staff member my tabs fill quickly and chat becomes very small.

**Comment by killjoy1221** [comment]
Sorry, my previous comment was meant for a different issue. Timestamps aren't implemented yet, nor are most of the settings.

**Comment by killjoy1221** [comment]
ec31a5c07016b7eaaab18cc3fe8e09e9068b862a
