### ISSUE TITLE
[1.8.9] Multi-project builds fail

### ISSUE THREAD

**Issue by killjoy1221** [killjoy1221/TabbyChat-2#50]
Waiting on MinecraftForge/ForgeGradle#347 and MinecraftForge/ForgeGradle#363

**Comment by Alvin-LB** [comment]
Just a question, would it not be possible to compile the two projects seperatly in the mean time? Just to get a 1.9 release out..

**Comment by killjoy1221** [comment]
I fixed this a while ago 87c5cbb5d636bd4cd80ebc26ee8fcf93091ca8db
