### ISSUE TITLE
[1.8.9] NullpointerException

### ISSUE THREAD

**Issue by Xiaminou** [killjoy1221/TabbyChat-2#51]
![2016-05-03_00 17 30](https://cloud.githubusercontent.com/assets/8670392/14969840/d5d6af50-10c4-11e6-827a-9fea83c30259.png)

I have never used liteloader before.
In the description of your mod you said "This can be used with either Forge or LiteLoader. The extension may be .jar, but it will work with LiteLoader unmodified."
Where can I find the jar file so I don't have to install Liteloader?

**Comment by killjoy1221** [comment]
You DO need Liteloader, but you can use Forge with it.  Besides, that
doesn't look like a invtweaks issue.  I'm not saying it  is its fault, but
it needs investigation.

**Comment by Xiaminou** [comment]
Well then the description is misleading, either way wouldn't it be much easier if it was a forge mod?

**Comment by killjoy1221** [comment]
This is an inventorytweaks issue. It injects an event into `GuiTextField.setFocused` and fails to ensure that it is initialized.

**Comment by killjoy1221** [comment]
Anyway, I fixed the description.

**Comment by Xiaminou** [comment]
did  you report it to them?

**Comment by killjoy1221** [comment]
No. You found the issue, so you should [report it](https://github.com/Inventory-Tweaks/inventory-tweaks/issues).

You might be interested in a [similar mod](http://minecraft.curseforge.com/projects/inventory-sorter) made by cpw.

**Comment by Xiaminou** [comment]
Well I'm no programmer so I wouldn't know what the problem is, you're the one with the knowledge to help fix the compatibility issue, please use it.
And inventory sorter is not even close to Inventory Tweaks, it only implements mousewheel like NEI did for 1.7.10, and I'm already using it.
Look if you don't put a little bit of effort into fixing compatibility issues, I don't see your mod being used by anyone.

**Comment by killjoy1221** [comment]
Fine. Go post in it with other information if you have it. (see above for referenced issue)

**Comment by killjoy1221** [comment]
Try the new version after it gets approved.

**Comment by Xiaminou** [comment]
Problem fixed, thank you.
