### ISSUE TITLE
TabbyChat chat window doesn't appear when also using Macromod (minecraft 1.10)

### ISSUE THREAD

**Issue by sfgasdfsafggfgg** [killjoy1221/TabbyChat-2#53]
When you press the button to open the chat window, it doesn't appear at all.

**Comment by killjoy1221** [comment]
The reason for this is obvious. I have not updated to 1.10 yet. It doesn't show up because liteloader doesn't load mods made for previous versions of minecraft. Either update it yourself or wait patiently for someone else to do it.
