### ISSUE TITLE
Chat Filter

### ISSUE THREAD

**Issue by veteranmina** [killjoy1221/TabbyChat-2#6]
(As said before, pointers to help)
Chat filter picks up anything that is in brackets i.e [LifeVIP], [Member] and such. I understand filter is just newly implemented.

**Comment by killjoy1221** [comment]
Is there an issue? I don't understand.

**Comment by veteranmina** [comment]
I am certain it is due to the settings for filtering is not set. But it filters everything into tabs at random that contain brackets. I'll get you pictures later tonight when I get home.
