### ISSUE TITLE
chat window remaining open

### ISSUE THREAD

**Issue by Scrael** [killjoy1221/TabbyChat-2#62]
Not sure if this is a bug or a feature, but either way its vastly irritating.
When I open the chat window with t or / and say something in chat or execute a command, rather then closing the chat window it remains open and I need to click escape to be able to move again. its a tiny thing but if it could be changed/fixed that would be great
http://imgur.com/a/z72Ct

**Comment by killjoy1221** [comment]
You have the chat pinned. Click the square in the top right corner of the
chat window.
