### ISSUE TITLE
Chatbox renders ontop or replaces playerlist etc

### ISSUE THREAD

**Issue by Brottweiler** [killjoy1221/TabbyChat-2#63]
When opening the playerlist, or voxelmap's fullscreen map (the one when you press X, not M), and also macro mod's player/block lists, the chat box renders ontop of it.

I reported this [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2181597-tabbychat-2-smp-chat-overhaul-new-maintainer?comment=595) some time ago but wanted to make an issue too incase it got unnoticed.

**Comment by killjoy1221** [comment]
This should resolve it.
https://github.com/killjoy1221/TabbyChat-2/commit/5a4f255d0ccdaf7e301bcc502a1946177eb4d668
