### ISSUE TITLE
Long lines severely drops fps

### ISSUE THREAD

**Issue by quasistar** [killjoy1221/TabbyChat-2#64]
Last night, I had hit / so I could do something on my other monitor (opening chat causes the game's mouse cursor to not dictate looking direction). When I came back in-game, I had forgotten and hit my tab key to see who was online. The list of server commands popped  up in chat and my fps immediately dropped from 60 vsync'd (typically around 150 when not vsync'd) to bouncing between 1 and 4. Removed mods until my fps returned to normal, and it turned out to be TabbyChat (only have 3 mods, so this was easy to confirm in numerous ways). Tried going to another server, but the fps was still extremely low. Tried updating (originally installed about a month ago, updated to the latest snapshot), to no avail. Tried removing log files, thinking TabbyChat must be reading them to fill the log when returning to play; no dice but I found out that the backlog (that's what I'm going to call it) didn't go away because I removed the logs. When that failed, I started typing up an issue here. When I finished I looked over at my other monitor and I was back at 60fps. Those long lines being in the backlog must have been flushed out by the chatter from players on the server.

Edit: To be more clear, what I typed was "/[tab]" .. in case that's confusing.

**Comment by Brottweiler** [comment]
I can confirm, typing a `/` and tabbing if it shows lots commands, severely drops the frames.

**Comment by killjoy1221** [comment]
e61f2ea

[download](https://drone.io/github.com/killjoy1221/TabbyChat-2/files)

**Comment by quasistar** [comment]
It fixes the 1-4 drop. I'd say this is resolved. There is a minor issue where new lines in chat drops fps for maybe half a second (I drop down to about 38 during that time).. but that's fine with me.

**Comment by killjoy1221** [comment]
I probably shouldn't mark it dirty if it's just a message being added. No
need to refresh the entire list

**Comment by killjoy1221** [comment]
I'm considering this fixed. Reply if you don't believe so.

**Comment by Brottweiler** [comment]
I think **long** lines causing fps drops is fixed, but I experience that if there are **many** lines it still causes FPS drops. Maybe every chat message causes FPS stutter, but it's not noticable, but if chat is spammed with many lines it still drops FPS.
