### ISSUE TITLE
Typing special characters executes macro GUI buttons

### ISSUE THREAD

**Issue by Brottweiler** [killjoy1221/TabbyChat-2#65]
Here's a video showcasing this bug: https://streamable.com/dtwk

As you can see, when I type some characters, all the GUI buttons are executed. You can notice this because the **Color** one executes, aswell as the **Me** one that is bound to run `/me $$!`. 

The characters I type you can see in the chat, it is `~`, `|` and `øæ¨`. Actually, all of these uses the key <kbd>Alt Gr</kbd>, but not all combinations with that key gives this issue.

**Comment by killjoy1221** [comment]
@Mumfrey thoughts on this?

**Comment by Mumfrey** [comment]
Have you assigned hotkeys to the buttons in question?

**Comment by Brottweiler** [comment]
@Mumfrey nope.

![](https://i.imgur.com/fPI1tJZ.png)

I can add that I use these versions:

- Liteloader 1.10.2-SNAPSHOT-rC9B4172-b8-8
- Macro mod 0.13.2
- MnmUtils 1.2.3-SNAPSHOT-142
- TabbyChat 2 2.1.2-SNAPSHOT-261

No other mods.

**Comment by Brottweiler** [comment]
Actually, the problem might be because it is **not** assigned to a key. It is assigned to `NONE`, maybe, and when I type `~`, it thinks I am pressing the `NONE` key. 

Adding a hotkey "fixes" it. I think the problem is Linux and keyboard layout, I've had issues before when key was bound to `NONE`, keys like the `§` key (where GRAVE is on US keyboards) would trigger it.

**Comment by Mumfrey** [comment]
How weird, you might be right though. Basically the combo is supposed to work as ALT+[hotkey] but maybe it's triggering on NONE as you say, which is odd since I check for it being a character key.

**Comment by Mumfrey** [comment]
I can probably fix it on macros end by just filtering the key event at the button level I guess.

**Comment by Brottweiler** [comment]
@Mumfrey I think this only happens with Tabbychat, not with normal chat, is it still a macros issue or is it a tabbychat issue?

**Comment by Mumfrey** [comment]
Probably both. Tabbychat is causing it but my code doesn't check for it.

**Comment by Brottweiler** [comment]
Not an issue anymore with the 1.11.2 versions of the mods.
