### ISSUE TITLE
Glitch with Stacking Msges

### ISSUE THREAD

**Issue by tyler489** [killjoy1221/TabbyChat-2#66]
when right clicking a blood alter with a division sidgil twice the came crashes im assuming this is do to the way bloodmagic stacks msg.
Using Direwolf 20's 1.10 modpack
http://pastebin.com/msAQk6Zr

**Comment by killjoy1221** [comment]
Should be fixed.
https://github.com/WayofTime/BloodMagic/issues/1035

**Comment by killjoy1221** [comment]
This should also fix it for mods which have the same issue.

95c7f2c571ce56ad6e1adbb579dee40ed80700ca
