### ISSUE TITLE
TabbyChat GUI error, thing?

### ISSUE THREAD

**Issue by iKarTehFox** [killjoy1221/TabbyChat-2#72]
So I have just downloaded the brand spankin' new TabbyChat for Minecraft 1.12. And yes, I know it's a Beta version, and I know it **will** contain a bug or 2 (or several). So when I press T or '/', there is no background to it, and the outlines of the GUI are surprisingly thick.

Here's a picture of what I mean:
![tabbychaterror](https://user-images.githubusercontent.com/17345571/27390332-9cf5b62a-5666-11e7-8ac2-f52485eada8b.PNG)

**Comment by Brottweiler** [comment]
>there is no background to it

What does this mean?

>the outlines of the GUI are surprisingly thick

It's the default. TabbyChat uses a [texture](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2181597-tabbychat-2-smp-chat-overhaul-new-maintainer?comment=739), which you can find [here](https://github.com/killjoy1221/TabbyChat-2/blob/master/src/main/resources/assets/tabbychat/textures/chatbox.png). You'll need to make a simple resource pack and add it, and edit it to make it like you want.

**Comment by killjoy1221** [comment]
Yeah... I haven't gotten around to drawing the background for the tray yet. I'll get around to it.

**Comment by killjoy1221** [comment]
https://github.com/killjoy1221/TabbyChat-2/commit/88adc6aeb449775f9142a6f4e00ce1d66f2413d4
