### ISSUE TITLE
[Request] Continue Supporting 1.11.2

### ISSUE THREAD

**Issue by CDAGaming** [killjoy1221/TabbyChat-2#73]
1.11.2 is still a very popular and stable version to use, and would be a shame to no longer support. Please Add at least a 1.11.2/1.11.x branch to continue support at least to v2.3.0

**Comment by killjoy1221** [comment]
Find bugs affecting it and I'll do that.

**Comment by CDAGaming** [comment]
For me at this time, i haven't seen any bugs (Might not be looking closely or just are not any that really effect my usage)

**Comment by killjoy1221** [comment]
Good. 1.11 is stable right now, though I will still support it if needed.
