### ISSUE TITLE
1.12 - Incompatibility - TrueType Font Replacement

### ISSUE THREAD

**Issue by XvSkItZvX** [killjoy1221/TabbyChat-2#74]
To begin with TabbyChat-2 is a beautiful and feature rich mod that I feel anyone who plays should look into. 

Unfortunately when used with the [TrueType Font Replacement](https://minecraft.curseforge.com/projects/truetype-font-replacement) mod, the cursor seems to lose alignment keeping the original spacing of vanilla text. The following images demonstrate the issues as well as highlight how this interferes with the fluidity of using the mod.

![tc2_no_text](https://user-images.githubusercontent.com/9143369/28803174-3e7fcb2e-7620-11e7-9cec-538bf91e9aee.PNG)
![tc2_not_much_text](https://user-images.githubusercontent.com/9143369/28803175-3e80bc28-7620-11e7-8adf-8c0ff2c230c7.PNG)
![tc2_a_bit_longer_text](https://user-images.githubusercontent.com/9143369/28803172-3e7b934c-7620-11e7-9936-e29b951cb502.PNG)

The following I circle the position of the cursor in blue.
![tc2_i_write_books](https://user-images.githubusercontent.com/9143369/28803176-3e8189c8-7620-11e7-80ff-6019fd4ae6af.PNG)

Below, the location I am trying to click on is red while the cursor position is circled in yellow.
![tc2_correcting_mistakes_are_hard](https://user-images.githubusercontent.com/9143369/28803173-3e7e1716-7620-11e7-9884-116d0a0b72e2.PNG)

**Comment by killjoy1221** [comment]
This also happens with just optifine and any HD font.

**Comment by XvSkItZvX** [comment]
I hadn't tested for Optifine as TTFR has caused issues with other UI mods in my pack. I do have optifine installed however, let me disable it and see if it still persists or if optifine is the culprit...

**Comment by killjoy1221** [comment]
This tool works fine. You'll just need to tweak the generated pack.mcmeta to make it work with 1.12.

http://mnm-mods.blogspot.com/2015/03/hd-font-generator.html

**Comment by XvSkItZvX** [comment]
After disabling Optifine the issue persisted...I'll have to check out the blog post and see if I can figure out how to use it..thanks for the reply.

**Comment by XvSkItZvX** [comment]
I see that this thread has been labeled as "bug", which I think means it will be looked into further. The following is simply the results of following your previous suggestions. 

I am using 44" Monitors at 1920x1090 resolution. 

After using the HD Font Generator, which was a very nifty little tool and much easier to figure out than I had expected, the alignment issues were corrected. 

Unfortunately text turned out small, thin, and difficult to read. This was tested using x32 and x512, with and without the unicode option, on "SansSerif.plain" and "SansSerif.bold" font (The same font that was used with TTFR) 

When using the new font generated with the HDFG, in combination with Optifine there was no change from the previous results. 

When using the TTFR mod in combination with the HDFG font (with and without optifine) there was a peculiar change in behavior. Instead of the cursor moving further away from the text as typed, the text began to pass the cursor. 

I hope this information proves useful, and if there is any other information I could provide feel free to let me know. 

Thanks for all your hard work.

**Comment by killjoy1221** [comment]
I am currently rewriting the cursor.

**Comment by XvSkItZvX** [comment]
Awesome I look forward to testing it on your next release, Thanks.
