### ISSUE TITLE
Unfocused chat is very transparent in multiplayer

### ISSUE THREAD

**Issue by Brottweiler** [killjoy1221/TabbyChat-2#77]
>I [reported](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2181597-tabbychat-2-smp-chat-overhaul-new-maintainer?comment=746) this on minecraftforums but not sure if it got acknowledged.

---

**Version**: `2.3.0-beta-296-mc1.12` (can't test 1.12.1 because it [crashes](https://gist.github.com/anonymous/c49d6da393cae23ac89651233f205ec3))

In multiplayer, when not having chat open, the background is very transparent, but when opening chat the background is more opaque

![](https://i.imgur.com/dKuVhOy.png)

This is a bug because it does not happen in singleplayer. I like this though as a feature, is it possible to make it so when chat is not opened, the background is 100% transparent?

**Comment by killjoy1221** [comment]
It seems to work fine for me. Can you test in 1.12.1 using the new version I just now uploaded?
(The crash was a problem with the build script and reobfuscation)

**Comment by Brottweiler** [comment]
Yeah I just tested it on a server and it doesn't seem to be an issue in 1.12.1. Would it be possible for this to be a feature though, like a separate image file for unfocused chat, so you can make that more transparent?
