### ISSUE TITLE
Voxelmap & TabbyChat cause error message

### ISSUE THREAD

**Issue by flcmc** [killjoy1221/TabbyChat-2#79]
Whenever I switch worlds on a multiworld server, this error shows up in my console.

[https://paste.ee/p/UXsxK](https://paste.ee/p/UXsxK)

I don't know whether the problem is on TabbyChat's Side or VoxelMap's.

**Comment by killjoy1221** [comment]
It's not going to cause any problems, though VoxelMap is doing things
wrong. I'm catching this to prevent a crash reported in #66
