### ISSUE TITLE
Hover Events not showing in the correct location

### ISSUE THREAD

**Issue by colin500** [killjoy1221/TabbyChat-2#80]
When i try to read a hover event it doesn't show up where it should be it instead shows up down further idk if this is because of the chat scale or what not but its be great if it were fixed :)

**Comment by killjoy1221** [comment]
Can you post some screenshots comparing it to the vanilla behavior?

**Comment by colin500** [comment]
sure

**Comment by colin500** [comment]
![2017-09-06_23 25 08](https://user-images.githubusercontent.com/11688661/30145996-0852d25a-935b-11e7-96e2-b06da81a8169.png)
TabbyChat^
![2017-09-06_23 27 24](https://user-images.githubusercontent.com/11688661/30145995-0852154a-935b-11e7-9aef-cfbf8e77868b.png)
Vanilla^

**Comment by colin500** [comment]
my mouse doesn't show but in vanilla i can point directly at the name and in the TabbyChat i have to move it down further

**Comment by killjoy1221** [comment]
Are you using the latest version?

**Comment by colin500** [comment]
i got it from the liteloader website.

**Comment by killjoy1221** [comment]
But what version? What's the file name?

**Comment by colin500** [comment]
2.3.0-beta-296

**Comment by killjoy1221** [comment]
Update to 2.3.1-mc1.12.1 and report back.

**Comment by colin500** [comment]
oh im using it for 1.12

**Comment by killjoy1221** [comment]
So test it on 1.12.1.

**Comment by colin500** [comment]
ok

**Comment by colin500** [comment]
yes it still does the same thing

**Comment by killjoy1221** [comment]
It seems to work for me. Are you able to build the current source and test using that?

**Comment by colin500** [comment]
yea i can

**Comment by colin500** [comment]
and if its because of this i am using this with optifine

**Comment by colin500** [comment]
i will do this tomorrow after school thanks for the help ill let you know if it works or not

**Comment by killjoy1221** [comment]
Be sure to try without optifine as well.

**Comment by colin500** [comment]
ok
actally ill do it now.

**Comment by killjoy1221** [comment]
Don't bother to say you're doing something. You can wait until after you do it so you can post the results at the same time.

**Comment by colin500** [comment]
ok

**Comment by colin500** [comment]
Yes it works fine in 1.12.1 after building it from github

**Comment by killjoy1221** [comment]
I'll be backporting to 1.11 at some point, but not 1.12.

**Comment by colin500** [comment]
fine, ill just port it up to 1.12 then... or at least try to...
