### ISSUE TITLE
Manually adding doesn't work properly.

### ISSUE THREAD

**Issue by xlJohnnyIcelx** [killjoy1221/TabbyChat-2#86]
I have this for 1.8.9 and 1.12.2. The 1.8.9 version works flawlessly but the 1.12.2 version doesn't. On my server we have a prefix for command spy [Spy] so I want this to have it's own tab and not show in the general tab. But when I add it manually as a filter it selects everything that starts with [ If I turn on automatic finding then it does it properly but doesn't hide it from the main chat of which I can't edit it to tell it to. Also I try to add pms as a custom filter aswell that would be separated from the main chat and that doesn't work either. Idk what is wrong because the 1.8.9 version works fine. Could it be a problem with Bungeecord making it not detect the servers properly?

**Comment by killjoy1221** [comment]
What is the filter you are using?

**Comment by xlJohnnyIcelx** [comment]
I took a screenshot https://i.imgur.com/jJjavoW.png

**Comment by xlJohnnyIcelx** [comment]
And here's the one I was also trying for Staff Chat https://i.imgur.com/bmkua69.png

**Comment by killjoy1221** [comment]
PMs are somewhat more advanced than usual filters. This is because it could be `Me -> You` or `You -> Me`. Depending on the plugin you're using, this could be different. HeroChat for example uses the `To You/From Me` format.

I suggest using a website such as [regexr](https://regexr.com) to test your filters.

**Comment by xlJohnnyIcelx** [comment]
Yeah my problem was if I didn't enable regular expressions nothing at all happened and if I did it just took everything starting with [ I guess I'll try that though. Again the pms weren't hard to do for me on Hypixel on 1.8.9 but doing the same thing on 1.12.2 didn't work

**Comment by xlJohnnyIcelx** [comment]
Okay well weird thing is now it works.. One last thing.. is there a way to disable them from lighting up red every time a new message appears in a specific tab?

**Comment by killjoy1221** [comment]
In general settings, there's a setting called unread flashing. Disable that.

**Comment by xlJohnnyIcelx** [comment]
But it already is and still does it.
