### ISSUE TITLE
Update version for 1.10.2

### ISSUE THREAD

**Issue by SubtypeZero** [killjoy1221/TabbyChat-2#88]
I'd like to see an updated version for 1.10.2 or another branch for it on GitHub that gets regularly updated along with the other versions. As it stands, there are several things that seem strange, broken, or are unimplemented in the 1.10.2 version. I realize this is a continuation of the original mod, but I'd certainly like to see some parts of the old GUI (like from the 1.5.2 version) come back to make it easier to configure. I'd also like to have the ability to enable match highlighting (not sure if this has been implemented for newer versions already).

**Comment by AlecZine** [comment]
I think this mod is dead for people like us that play on 1.10.2... i would like to see this fixed :(

**Comment by liach** [comment]
Yep, the mod is focusing on 1.12 now. It left 1.10.2 before a few important bug fixes from its dependents were pushed.
