### ISSUE TITLE
Network Disconnect: A fatal error has occurred, this connection is terminated

### ISSUE THREAD

**Issue by Mohron** [killjoy1221/TabbyChat-2#89]
mod-tabbychat-2.3.3-mc1.12.2
liteloader-1.12.2-SNAPSHOT-release
environmentaltech-1.12.2-2.0.6b
Forge-14.23..1.2565

https://hastebin.com/jojuwabama.php

When using Tabby Chat with environmental tech clicking a controller disconnects you from an smp server.
https://hastebin.com/jojuwabama.php

**Comment by Mohron** [comment]
https://github.com/ValkyrieofNight/EnvironmentalTech/issues/90

**Comment by killjoy1221** [comment]
6cf08216d642ed9697ccbb34b418badcb77cce9f

This should make it not crash hopefully, but mods not scheduling their packet logic is asking for trouble.

**Comment by Mohron** [comment]
Thanks for the fix. Hopefully there will be a proper fix on the mod side as well.

**Comment by Mohron** [comment]
Will this fix be finding its way to Curse in the near future?

**Comment by killjoy1221** [comment]
Uploaded to curse.

version: `2.3.4`
