### ISSUE TITLE
Chat Continuation

### ISSUE THREAD

**Issue by Malvagio87** [killjoy1221/TabbyChat-2#9]
Chat continuation does not appear to be working.  

For instance if i type "/r This is a really long sentence that exceeds the amount of words accepted by minecraft to send to another player and or to the server because the default chat is terrible and Tabby Chat is the only thing that makes it better which is why I am so glad it is being developed for 1.8."  It would break up the sentence and send it as 2 or 3 different entries.

Right now all that gets sent is "/r This is a really long sentence that exceeds the amount of words accepted by minecra" and that is it even though i can type in the entire thing.  I believe what it used to do was take the command line and re-enter it after each break. but i could be wrong.

Hope these issues help and thanks for taking the time to update the plugin.

**Comment by killjoy1221** [comment]
This is not implemented yet.
