### ISSUE TITLE
TabbyChat's issue with Pixelmon Reforged on 1.12.2

### ISSUE THREAD

**Issue by poqdavid** [killjoy1221/TabbyChat-2#90]
When TabbyChat-2.3.4-mc1.12.2 is used with PixelmonReforged-1.12.2-6.1.0 while in battle you can't see the chat msgs.

**Comment by killjoy1221** [comment]
I've looked into this for a bit. Unfortunately, this isn't something I can fix. Pixelmon, it seems, is drawing the chat from scratch. This means the changes I'm adding to it are not applied.
