### ISSUE TITLE
Even partial regex matches are picked up in filters

### ISSUE THREAD

**Issue by MusicScore** [killjoy1221/TabbyChat-2#91]
Let's say my server is spamming me with "`test`". I'm reasonably annoyed, and use TabbyChat to set up a filter to hide the server's "`test`" spam.

If I use raw input or regex, even a partial match erases the whole message. I used this filter expression as a test:
```
test
```

And any message containing "test" will be erased, even if I'm the one sending the message. An example of such a message is:
`<MusicScore> hi my name is test`
versus the actual raw text I want to hide, which is just
`test`

Is there a way to work around this?

**Comment by killjoy1221** [comment]
By default, regex is set to match anywhere in the string. If you want it to match exact, you need to add `^` and `$` into the expression. They mean start and end respectively.

I suggest reading up more on filters on the [wiki page.](../wiki/Filters)
