### ISSUE TITLE
Can I custom the delims?

### ISSUE THREAD

**Issue by AaronHzy** [killjoy1221/TabbyChat-2#93]
Hi! Can I custom the delims（Prefix）?
Like "★ Prefix >>"
Identifying the tags within the "★" and ">>"

**Comment by killjoy1221** [comment]
Yes. Create a new filter and use a regex pattern using groups. This is an
advanced feature, so I suggest picking up regular expressions.

**Comment by AaronHzy** [comment]
Is there a tutorial?

**Comment by killjoy1221** [comment]
Do you really want chat to overlap your hotbar?
