### ISSUE TITLE
Unused @Redirect

### ISSUE THREAD

**Issue by pKalju** [killjoy1221/TabbyChat-2#96]
Remove this unused `@Redirect` in:
https://github.com/killjoy1221/TabbyChat-2/blob/master/src/main/java/mnm/mods/tabbychat/core/mixin/MixinGuiChat.java

It is conflicting with a another mod, `Skipping ... already redirected by mixin.tabbychat.json:MixinGuiChat->@Redirect::redirect$onDrawScreen$zzc000(IIIII)V with priority 1000.`

```
@Redirect(
            method = "drawScreen(IIF)V",
            require = 1,
            at = @At(
                    value = "INVOKE",
                    target = "Lnet/minecraft/client/gui/GuiChat;drawRect(IIIII)V"))
    private void onDrawScreen(int x1, int y1, int x2, int y2, int color) {
        // noop
    }
```

**Comment by killjoy1221** [comment]
No, I need that there. If it wasn't there, the textbox would be rendered, which I don't want.

**Comment by killjoy1221** [comment]
If you want it done first, increase your priority.
