### ISSUE TITLE
Remove black coutour

### ISSUE THREAD

**Issue by LeChikito** [killjoy1221/TabbyChat-2#99]
Hi,
I have search unsuccessfully a way to remove the black coutour of the chat in 1.12.2.
Is there an option, or is it possible to add it?
Thanks,
LeChikito
![image](https://user-images.githubusercontent.com/34887668/50924000-97e6ca00-144e-11e9-9c54-0a6be664802b.png)

**Comment by killjoy1221** [comment]
The chat box is texture based, so you can open the png in gimp to remove
the outline. You can then load it on a resource pack.

I forget the exact location of the texture, but it's probably the only
texture in the litemod.

**Comment by LeChikito** [comment]
hum i have to use the .jar file, the litemod encounter a conlict on my server.
I will search it and come back to tell you if i have find it (or not)
Thanks

**Comment by killjoy1221** [comment]
Using the latest forge should fix any compatibility issue with liteloader.
